export const CURRENCY_SET_CURRENCY = "CURRENCY_SET_CURRENCY";
export const CURRENCY_TOGGLE_LOADING = "CURRENCY_TOGGLE_LOADING";
export const CURRENCY_BASE = "CURRENCY_BASE";

export const RATES_REQUEST = "RATES_REQUEST";
export const RATES_SUCCESS = "RATES_SUCCESS";
export const RATES_ERROR = "RATES_ERROR";
